// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDof08Ez5Z4r08HLSXY4-7BAH5TgjOpl_w',
    appId: '1:319787503019:web:d9b5d4e1b0063661a956ee',
    messagingSenderId: '319787503019',
    projectId: 'ratejacobs-e63c7',
    authDomain: 'ratejacobs-e63c7.firebaseapp.com',
    storageBucket: 'ratejacobs-e63c7.appspot.com',
    measurementId: 'G-EKHXS2256V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkJJFDwJZopjTikKE1dAJ55geiCuFzyU0',
    appId: '1:319787503019:android:b9e3577848b8b51aa956ee',
    messagingSenderId: '319787503019',
    projectId: 'ratejacobs-e63c7',
    storageBucket: 'ratejacobs-e63c7.appspot.com',
  );
}
